name: Update Profile Image

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run the script
        env:
          GITHUB_TOKEN: ${{ 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 }}  # Use your secret here
        run: python update_tryhackme.py  # Use the correct file name
