name: Update TryHackMe

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Change to your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install requests library
          pip install json  # json is part of the Python Standard Library, no need to install
          pip install time  # time is also part of the Python Standard Library, no need to install
          pip install regex  # install regex if you are using it
          pip install subprocess  # subprocess is also part of the Standard Library
        # Add other libraries as needed

      - name: Run update_tryhackme.py
        run: python update_tryhackme.py
