name: Update Profile Image

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install requests  # Add any other dependencies your script requires

      - name: Run the script
        run: python update_tryhackme.py  # Ensure this is the correct path to your script

      - name: Commit changes
        run: |
          git config --local user.name "Gaurav-Jangid-730"
          git config --local user.email "gauravjangid7300@gmail.com"
          git add Readme.md  # Make sure to specify the correct README file name
          git commit -m "Update profile image URL" || echo "No changes to commit"

      - name: Push changes
        run: git push
