name: Update TryHackMe

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Change to your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install requests library
          pip install regex  # Install regex if you are using it
          # No need to install json, time, or subprocess

      - name: Run update_tryhackme.py
        run: python update_tryhackme.py
