name: Update TryHackMe Badges

on:
  # Runs the action every day at midnight (UTC)
  schedule:
    - cron: "0 0 * * *"
  # Allows manual trigger of the workflow
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Python script to update README
        run: |
          python update_tryhackme.py

      - name: Commit and push changes
        run: |
          git config --local user.email "gauravjangid7300@gmail.com"
          git config --local user.name "Gaurav-Jangid-730"
          git add README.md
          git commit -m "Update TryHackMe stats"
          git push
