name: Update Profile Image
on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run the script
        run: python update_tryhackme.py  # Use the correct file name

      - name: Commit and push changes
        run: |
          git config --local user.name "Gaurav-Jangid-730"
          git config --local user.email "gauravjangid7300@gmail.com"
          git add Readme.md
          git commit -m "Update README with new profile image" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}  # Replace with your secret name

